name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [ x86, x64 ]
    steps:
    - name: Check Tag
      id: check-tag
      uses: actions-ecosystem/action-regex-match@v2
      with:
        text: ${{ github.ref_name }}
        regex: '^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$'

    - name: Fail if invalid
      if: steps.check-tag.outputs.match == ''
      uses: Actions/github-script@v3
      with:
        script: |
          core.setFailed('Invalid tag')
    
    - uses: microsoft/setup-msbuild@v1

    - uses: abel0b/setup-premake@v2
      with:
        version: "5.0.0-beta1"

    - uses: nuget/setup-nuget@v1

    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Build SUWSF
      run: |
        nuget restore SUWSF.sln
        msbuild SUWSF.sln -p:Configuration=Release -p:Platform=${{ matrix.platform }} -p:BUILDVERSION="${{ github.ref_name }}"
    
    - name: Premake Ultimate ASI Loader
      run: |
        ./premake5.bat
      working-directory: ./external/Ultimate-ASI-Loader

    - name: Setup DXSDK
      run: "if (-not (Test-Path env:DXSDK_DIR)) \n{\nStart-FileDownload 'https://download.microsoft.com/download/A/E/7/AE743F1F-632B-4809-87A9-AA1BB3458E31/DXSDK_Jun10.exe' -FileName 'C:\\DXSDK_Jun10.exe'\nStart-FileDownload 'https://raw.githubusercontent.com/chocolatey/choco/master/src/chocolatey.resources/redirects/RefreshEnv.cmd' -FileName 'C:\\RefreshEnv.cmd'\nStart-Process \"C:\\DXSDK_Jun10.exe\" \"/F /S /O /U\" -NoNewWindow -Wait\nC:\\RefreshEnv.cmd\n}"

    - name: Build Ultimate ASI Loader x64
      if: ${{ matrix.platform == x64 }}
      run: |
        msbuild ./external/Ultimate-ASI-Loader/build/Ultimate-ASI-Loader-${{ matrix.platform }}.sln -p:Configuration=Release -p:Platform=${{ matrix.platform }} -p:TargetName=dsound -p:OutDir="../../../${{ matrix.platform }}/Release" -p:PlatformToolset=v142

    - name: Build Ultimate ASI Loader x86
      if: ${{ matrix.platform == x86 }}
      run: |
        msbuild ./external/Ultimate-ASI-Loader/build/Ultimate-ASI-Loader-${{ matrix.platform }}.sln -p:TargetName=dsound -p:OutDir="../../../${{ matrix.platform }}/Release" -p:PlatformToolset=v142
        
    - name: Prepare for release
      run: |
        rm ${{ matrix.platform }}/Release/*.pdb
        copy README.md ${{ matrix.platform }}/Release/
        copy LICENSE ${{ matrix.platform }}/Release/
        copy SUWSF.ini ${{ matrix.platform }}/Release/
        7z a -tzip "SUWSF-${{ matrix.platform }}.zip" "./${{ matrix.platform }}/Release/*"

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: "SUWSF-${{ matrix.platform }}.zip"
        draft: true
    

    
