name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Check Tag
      id: check-tag
      uses: actions-ecosystem/action-regex-match@v2
      with:
        text: ${{ github.ref_name }}
        regex: '^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$'

    - name: Fail if invalid
      if: steps.check-tag.outputs.match == ''
      uses: Actions/github-script@v3
      with:
        script: |
          core.setFailed('Invalid tag')
    
    - uses: microsoft/setup-msbuild@v1

    - uses: abel0b/setup-premake@v2
      with:
        version: "5.0.0-beta1"

    - uses: nuget/setup-nuget@v1

    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build SUWSF
      run: |
        nuget restore SUWSF.sln
        msbuild SUWSF.sln -p:Configuration=Release -p:Platform=x64 -p:BUILDVERSION="${{ github.ref_name }}"
    
    - name: Premake Ultimate ASI Loader
      run: |
        ./premake5.bat
      working-directory: ./external/Ultimate-ASI-Loader

    - name: Build Ultimate ASI Loader
      run: |
        msbuild ./external/Ultimate-ASI-Loader/build/Ultimate-ASI-Loader-x64.vcxproj -t:Build -p:Configuration=Release -p:Platform=x64 -p:TargetName=dsound -p:OutDir="../../../x64/Release" -p:PlatformToolset=v142

    - name: Prepare for release
      run: |
        rm x64/Release/*.pdb
        copy README.md x64/Release/
        copy LICENSE x64/Release/
        copy SUWSF.ini x64/Release/
        7z a -tzip "SUWSF.zip" "./x64/Release/*"

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: "SUWSF.zip"
        draft: true
    

    
